# Generated by Django 5.2.7 on 2025-10-07 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Текст уведомления')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показывать')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Техническое уведомление',
                'verbose_name_plural': 'Технические уведомления',
            },
        ),
    ]
