# Generated by Django 5.2.7 on 2025-10-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['sort', 'id'], 'verbose_name': 'Платежный метод', 'verbose_name_plural': 'Платежные методы'},
        ),
    ]
