apiVersion: v1
kind: Service
metadata:
  name: main-app
  namespace: evpay
spec:
  selector:
    app: main-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: media
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pay-api
  namespace: evpay
spec:
  selector: { app: pay-api }
  ports: [{ port: 8000, targetPort: 8000 }]