apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: evpay
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: web
        image: docker.io/b1yaka/ewovaleron-pay-web:latest
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -lc
          - python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 60
        ports:
          - containerPort: 8000
        env:
          - name: DJANGO_DEBUG
            value: "0"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: evpay-secrets
                key: DJANGO_SECRET_KEY
          - name: DATABASE_URL
            value: postgresql://postgres:postgres@pg.evpay.svc.cluster.local:5432/ev_main
          - name: REDIS_URL
            value: redis://redis.evpay.svc.cluster.local:6379/0
          - name: RABBIT_URL
            value: amqp://user:pass@rabbit.evpay.svc.cluster.local:5672/%2F
          - name: PAY_API_URL
            value: http://pay-api.evpay.svc.cluster.local:8000
          - name: ALLOWED_HOSTS
            value: evpayservice.com,pay.evpayservice.com
          - name: CSRF_TRUSTED_ORIGINS
            value: https://evpayservice.com,https://pay.evpayservice.com
          - name: MEDIA_ROOT
            value: /app/media
          - name: MEDIA_URL
            value: /media/
          - name: PAY_INTERNAL_TOKEN
            value: "3cf592a2dfe6ef7297f567e134e791bf9a87e8d13adb63ba15103129772d7e81"
          - name: PAY_LINK_TTL_HOURS
            value: "24"
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
            httpHeaders:
              - name: Host
                value: evpayservice.com
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 6

        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
            httpHeaders:
              - name: Host
                value: evpayservice.com
          initialDelaySeconds: 20
          periodSeconds: 10

        volumeMounts:
          - name: media
            mountPath: /app/media

      - name: media-nginx
        image: nginx:alpine
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: media
            mountPath: /media
          - name: media-nginx-conf
            mountPath: /etc/nginx/conf.d
        command: ["/bin/sh","-lc","nginx -g 'daemon off;'"]

      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: media-nginx-conf
          configMap:
            name: media-nginx-conf
