apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-api
  namespace: evpay
spec:
  replicas: 2
  selector: { matchLabels: { app: pay-api } }
  template:
    metadata: { labels: { app: pay-api } }
    spec:
      containers:
      - name: api
        image: docker.io/b1yaka/ewovaleron-pay-api:latest
        command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
        ports: [{ containerPort: 8000 }]
        env:
        - { name: DATABASE_URL, value: "postgresql://postgres:postgres@pg-postgresql.evpay.svc.cluster.local:5432/ev_pay" }
        - { name: REDIS_URL,     value: "redis://redis-master.evpay.svc.cluster.local:6379/1" }
        - { name: RABBIT_URL,    value: "amqp://user:pass@rmq-rabbitmq.evpay.svc.cluster.local:5672//" }
        - { name: FREKASSA_MERCHANT_ID, value: "66169" }
        - { name: FREKASSA_API_KEY, value: "455116e47360f7f9442b95cad91d88db" }
        - { name: FREKASSA_SECRET_KEY, value: "wV.%os.K!gSg5bc" }
        readinessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 1
          failureThreshold: 3
        livenessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 1
          failureThreshold: 3