apiVersion: batch/v1
kind: Job
metadata:
  name: main-migrate
  namespace: evpay
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: docker.io/b1yaka/ewovaleron-pay-web:latest
        command: ["bash","-lc","python manage.py migrate && python manage.py collectstatic --noinput || true"]
        env:
        - { name: DJANGO_DEBUG, value: "0" }
        - { name: SECRET_KEY, valueFrom: { secretKeyRef: { name: evpay-secrets, key: DJANGO_SECRET_KEY } } }
        - { name: DATABASE_URL, value: "postgresql://postgres:postgres@pg-postgresql.evpay.svc.cluster.local:5432/ev_main" }
        - { name: REDIS_URL,     value: "redis://redis-master.evpay.svc.cluster.local:6379/0" }
        - { name: RABBIT_URL,    value: "amqp://user:pass@rmq-rabbitmq.evpay.svc.cluster.local:5672//" }