apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-listener
  namespace: evpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-listener
  template:
    metadata:
      labels:
        app: payment-listener
    spec:
      containers:
      - name: listener
        image: docker.io/b1yaka/ewovaleron-pay-web:latest
        command: ["/bin/sh", "-lc", "python manage.py payment_listener"]
        env:
        - { name: DJANGO_DEBUG, value: "0" }
        - name: SECRET_KEY
          valueFrom: { secretKeyRef: { name: evpay-secrets, key: DJANGO_SECRET_KEY } }
        - { name: DATABASE_URL, value: "postgresql://postgres:postgres@pg.evpay.svc.cluster.local:5432/ev_main" }
        - { name: REDIS_URL,     value: "redis://redis.evpay.svc.cluster.local:6379/0" }
        - { name: CELERY_BROKER_URL, value: "amqp://user:pass@rabbit.evpay.svc.cluster.local:5672//" }
        - { name: CELERY_RESULT_BACKEND, value: "redis://redis.evpay.svc.cluster.local:6379/1" }
        - { name: RABBIT_URL,    value: "amqp://user:pass@rabbit.evpay.svc.cluster.local:5672/%2F" }
        - { name: PAY_API_URL,   value: "http://pay-api.evpay.svc.cluster.local:8000" }
        - { name: PAY_INTERNAL_TOKEN, value: "3cf592a2dfe6ef7297f567e134e791bf9a87e8d13adb63ba15103129772d7e81" }
        - { name: ALLOWED_HOSTS, value: "evpayservice.com,pay.evpayservice.com" }
        - { name: CSRF_TRUSTED_ORIGINS, value: "https://evpayservice.com,https://pay.evpayservice.com" }
