# Generated by Django 5.2.7 on 2025-10-06 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=32)),
                ('order_prefix', models.CharField(max_length=3)),
                ('order_date', models.DateField()),
                ('order_seq', models.PositiveIntegerField()),
                ('payment_id', models.CharField(max_length=64, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('fk_url', models.URLField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.EmailField(max_length=254)),
                ('method', models.PositiveIntegerField(default=36)),
                ('comment', models.CharField(blank=True, max_length=140)),
                ('tag', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'order_date', 'order_seq')},
            },
        ),
        migrations.CreateModel(
            name='SellerDayCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day')},
            },
        ),
    ]
