name: "tg-bot: build & deploy"

on:
  push:
    branches: [ main ]
    paths:
      - 'bot/**'
      - 'main-app/**'
      - 'k8s/04-bot.yaml'
      - '.github/workflows/bot.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: bot/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ewovaleron-pay-bot:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ewovaleron-pay-bot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'
      - name: Write kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          printf "%s" "$KUBE_CONFIG" > ~/.kube/config
      - name: Update image (tg-bot)
        run: |
          set -e
          kubectl -n evpay set image deployment/tg-bot tg-bot=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ewovaleron-pay-bot:${{ github.sha }}
          kubectl -n evpay rollout status deployment/tg-bot --timeout=180s
