name: "pay-api: build & deploy"

on:
  push:
    branches: [ main ]
    paths:
      - 'pay-api/**'
      - 'k8s/05-pay-deploy.yaml'
      - '.github/workflows/pay-api.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./pay-api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ewovaleron-pay-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ewovaleron-pay-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'

      - name: Write kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          printf "%s" "$KUBE_CONFIG" > ~/.kube/config

      - name: Update image (pay-api only)
        run: |
          set -e
          kubectl -n evpay set image deployment/pay-api api=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ewovaleron-pay-api:${{ github.sha }}
          kubectl -n evpay rollout status deployment/pay-api --timeout=180s
